<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BcDepAnalyzer.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Scripts\*.sql" />
  </ItemGroup>
</Project>
